#!/usr/bin/env bash

PLUGIN_DIR="$HOME/.config/xournalpp/plugins"
LOCAL_EXAMPLE_PLUGIN_DIRS=(*/)

for LOCAL_EXAMPLE_PLUGIN_DIR in "${LOCAL_EXAMPLE_PLUGIN_DIRS[@]}"
do
    EXAMPLE_PLUGIN_DIR="$PLUGIN_DIR/$LOCAL_EXAMPLE_PLUGIN_DIR"
    rm -rf "$EXAMPLE_PLUGIN_DIR"
    cp -r "$LOCAL_EXAMPLE_PLUGIN_DIR" "$EXAMPLE_PLUGIN_DIR"
done
