#!/usr/bin/env bash

PLUGIN_DIR="$HOME/.config/xournalpp/plugins"
ICON_DIR="$HOME/.local/share/icons"
LOCAL_EXAMPLE_PLUGIN_DIRS=(*/)
LOCAL_EXAMPLE_PLUGIN_ICONS=(**/*.svg)

for LOCAL_EXAMPLE_PLUGIN_DIR in "${LOCAL_EXAMPLE_PLUGIN_DIRS[@]}"
do
    EXAMPLE_PLUGIN_DIR="$PLUGIN_DIR/$LOCAL_EXAMPLE_PLUGIN_DIR"
    echo "Copy plugin $LOCAL_EXAMPLE_PLUGIN_DIR to $EXAMPLE_PLUGIN_DIR"
    rm -rf "$EXAMPLE_PLUGIN_DIR"
    cp -r "$LOCAL_EXAMPLE_PLUGIN_DIR" "$EXAMPLE_PLUGIN_DIR"
done
mkdir -p "$ICON_DIR"
for LOCAL_EXAMPLE_PLUGIN_ICON in "${LOCAL_EXAMPLE_PLUGIN_ICONS[@]}"
do
    PLUGIN_NAME=`basename "$LOCAL_EXAMPLE_PLUGIN_ICON"`
    EXAMPLE_PLUGIN_ICON_FILE="$ICON_DIR/$PLUGIN_NAME"
    echo "Copy plugin icon $LOCAL_EXAMPLE_PLUGIN_ICON to $EXAMPLE_PLUGIN_ICON_FILE"
    rm -f "$EXAMPLE_PLUGIN_ICON_FILE"
    cp "$LOCAL_EXAMPLE_PLUGIN_ICON" "$EXAMPLE_PLUGIN_ICON_FILE"
done
