[about]
author=AnonymerNiklasistanonym
description=Registers keyboard shortcuts for e.g. easy tablet auxiliary key integration
version=1.0

[default]
# Enabled per default
enabled=true

[plugin]
# The main script file
mainfile=main.lua
